### PR TITLE
pin sklearn exactly to 0.24.0 

### PR DESCRIPTION
**Pull request by LWprogramming**
in case minibatchkmeans unpickling ends up being an issue. This is the only place scikit-learn appears in the repo based on my grep.

### CODE REVIEW

**Comment by lucidrains** [comment]
nice! thank you! want to bump the version while you are at it?

**Comment by lucidrains** [comment]
awesome!

**Comment by rsxdalv** [comment]
this causes scikit-learn to be built on the installer's machine, resulting in:

https://github.com/lucidrains/audiolm-pytorch/issues/182
https://github.com/rsxdalv/tts-generation-webui/issues/61

**Comment by lucidrains** [comment]
@LWprogramming do you know which version of scikit-learn the minibatchmeans stops working?

**Comment by lucidrains** [comment]
for reference, don't see any restrictions for the fairseq package https://github.com/facebookresearch/fairseq/blob/main/setup.py#L191

**Comment by lucidrains** [comment]
oh i see the error message now

ok, what i'm going to do is allow setup.py to still work, but just add an assert if hubert is being used

**Pull request merged**
