### PR TITLE
changed to s3 support

### PR DESCRIPTION
**Pull request by marianna13**
Broken dataloader.

### CODE REVIEW

**Comment by lucidrains** [comment]
@marianna13 oh i see, thanks for this Marianna! i will do an in-depth review early next week and we can try to get it merged next friday? looking at the changes, it may need some work

**Comment by marianna13** [comment]
@lucidrains no don't merge it yet, it's broken, I just want to make it work

**Comment by lucidrains** [comment]
@marianna13 ok cool! support for Romain's cc2dataset would definitely be ideal at some point

you can mark your pull request as a draft, if you want the maintainer to know it isn't ready for review. pro tip

**Comment by lucidrains** [comment]
@marianna13 while you try to get it functional, i can come meet you from the other end

maybe for starters allow for custom train and valid datasets to be passed into the trainers?

**Comment by marianna13** [comment]
@lucidrains yeah it would be nice! thanks

**Pull request closed without merging**
